apiVersion: v1
kind: ConfigMap
metadata:
  name: angie-chacon-front-configmap
  labels:
    app: angie-chacon-front
data:
  default.conf.template: |
    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html;

        # Configuraci√≥n para SPA de Angular
        location / {
            try_files $uri $uri/ /index.html;
        }

        # Proxy para la API - apunta al servicio de Kubernetes
        location /api/ {
            proxy_pass http://angie-chacon-back-service:8088/api/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_cache_bypass $http_upgrade;
        }
    }

