apiVersion: v1
kind: Service
metadata:
  name: angie-chacon-back-service
  namespace: angie-chacon
  labels:
    app: angie-chacon-back
spec:
  type: NodePort
  selector:
    app: angie-chacon-back
  ports:
  - name: http
    port: 8088
    targetPort: 8088
    nodePort: 30088
    protocol: TCP

