apiVersion: v1
kind: Service
metadata:
  name: angie-chacon-front-service
  namespace: angie-chacon
  labels:
    app: angie-chacon-front
spec:
  type: NodePort
  selector:
    app: angie-chacon-front
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP

